### ISSUE TITLE
Not able to install the plugin

### ISSUE THREAD

**Issue by sanchos** [kurt-cb/pytest-ads-testplan#1]
When trying to install via pip installation process finishing with error:

pip install pytest-ads-testplan
```

Collecting pytest-ads-testplan
  Using cached pytest-ads-testplan-0.0.4.tar.gz (18 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/32/txr_60b150q2_g04bch2nctm0000gn/T/pip-install-oqwdq0ei/pytest-ads-testplan_ebe755c47389434588da2703ba4b4ae5/setup.py", line 7, in <module>
          with open('requirements.txt','r') as r:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.

```

**Comment by aronpaljakab** [comment]
I am facing the same issue when using the pip install command. Locally I could install the project using the setup.py, however, not in Azure Pipeline...

**Comment by rouzbeh** [comment]
Same thing here

**Comment by ErmolovaIrina** [comment]
So far, nothing change

**Comment by ahmedsza** [comment]
Same issue.  not yet 100% but I was able to take this repo - and then publish it as a package in azure artefacts, then install the pip package from azure artefacts in the pipeline- that seems to be working. Not sure why the published version is not working..
